[buildPlans.iosevka-my-mono]
family = "Iosevka My Mono"
spacing = "fixed"
serifs = "sans"
no-cv-ss = false
exportGlyphNames = true
hintParams = "none"

[buildPlans.iosevka-my-mono.variants.design]

[buildPlans.iosevka-my-mono.weights.regular]
shape = 400
menu = 400
css  = 400

[buildPlans.iosevka-my-mono.weights.medium]
shape = 500
menu = 500
css  = 500

[buildPlans.iosevka-my-mono.weights.semibold]
shape = 600
menu = 600
css  = 600

[buildPlans.iosevka-my-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css  = "normal"
